version: '3.5'

services:
  user-backend:
    build: .
    ports:
      - "8030:8030"
    environment:
      - PROFILE=staging

  user-db:
    image: postgres:14.6
    ports:
      - "5430:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=user
    volumes:
      - schedule-db-volume:/var/lib/postgresql/data

volumes:
  schedule-db-volume:


